version: "3.3"

# Note: Ports 8000, 8001 and 8002 are reserved for the services
services:

  required:
    image: alpine:latest
    depends_on:
      - es7
      - db

  monitoring:
    image: alpine:latest
    depends_on:
      - kibana7
      - adminer

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es7
    environment:
      - discovery.type=single-node
    ports:
      - "8003:9200"
    volumes:
      - locations-es7:/usr/share/elasticsearch

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      ELASTICSEARCH_HOSTS: http://es7:9200/
    ports:
      - "8004:5601"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kek
      POSTGRES_USER: lol
      POSTGRES_DB: users
    ports:
      - "8005:5432"

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kek
      POSTGRES_USER: lol
      POSTGRES_DB: users
    ports:
      - "8006:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN='nette'
    ports:
      - "8007:8080"


volumes:
  locations-es7: