version: "3.3"

services:
  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es7
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:8001:9200"
    volumes:
      - locations-es7:/usr/share/elasticsearch

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      ELASTICSEARCH_HOSTS: http://es7:9200/
    ports:
      - "127.0.0.1:8002:5601"

volumes:
  locations-es7: